// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-t64ZTYZkPkIR5aWSnUD-3QbsaAd7LrY',
    appId: '1:214603068296:android:978fbc312d4206878cc03d',
    messagingSenderId: '214603068296',
    projectId: 'stockpulse-fc5af',
    storageBucket: 'stockpulse-fc5af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhrB4-PS_-5AVrETrcqlMEu3foNE1aZOY',
    appId: '1:214603068296:ios:e23cf20ce551eaa68cc03d',
    messagingSenderId: '214603068296',
    projectId: 'stockpulse-fc5af',
    storageBucket: 'stockpulse-fc5af.firebasestorage.app',
    androidClientId: '214603068296-3vrnoavno8la6jkjru5e6eoi1tiqns0o.apps.googleusercontent.com',
    iosClientId: '214603068296-d6foe478q4if13rolu69lfjskq7hiuab.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockpulse2',
  );
}
